version: '3'
services:
  web:
    container_name: lobby
    build: .
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - lobby-net
  db:
    container_name: lobby_db
    image: postgres:latest
    healthcheck:
      test: ["CMD", "pg_isready", "-q"]
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: lobby_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: testpwd
    networks:
      - lobby-net
networks:
  lobby-net:
    driver: bridge
